spartatdd/polls/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.result, name='result'),
]

spartatdd/spartatdd/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

spartatdd/polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

spartatdd/polls/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from django.shortcuts import get_object_or_404, render
from django.utils import timezone
from .models import Question


...

def result(request, question_id):
    question = get_object_or_404(Question, pk=question_id, pub_date__lte=timezone.now())
    return render(request, 'polls/result.html', {'question': question})

spartatdd/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }}</li>
    {% endfor %}
</ul>
<a href="/polls/{{ question.id }}/results/">
    투표 결과 보기
</a>

<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <p>Choice: {{ choice.choice_text }}</p>
    <p>Vote Count: {{ choice.votes}}</p>
{% endfor %}
</ul>

spartatdd/polls/templates/polls/index.html
{% if question_list %}
    <ul>
        {% for question in question_list %}
            <li>{{ question.question_text }}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>등록된 설문조사가 없습니다.</p>
{% endif %}

<ul>
    {% for question in question_list %}
    <li>{{ question.question_text }}</li>
    {% endfor %}
</ul>